version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c 'npm run dev'
    tty: true
    stdin_open: true
    environment:
      HOST: 0.0.0.0
    ports:
      - 1234:3000
    volumes:
      - .:/nuxt_practice
